name: CI
on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Build & Test on Ubuntu
    strategy:
      matrix:
        go-version: ["stable"] # or specific versions like "1.21", "1.22"
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools gcc-multilib

      - name: Build (Linux 386 static)
        run: |
          CC="musl-gcc" \
          CGO_ENABLED=1 \
          GOOS=linux \
          GOARCH=386 \
          go build \
            -ldflags="-s -w -linkmode external -extldflags '-static'" \
            -v .
          ls -al

      - uses: actions/upload-artifact@v4
        with:
          name: chisel
          path: ./*
